language: go
go:
- '1.5'
sudo: true
dist: precise
group: edge
env:
  global:
  - CF_APP=go-cloudant
  - CF_SPACE=demos
  - secure: "wIlmqhVLqWRPxzFpv0H5mp2eSsrEW5CdgIU3/X99QTqCOyP0n/NbAXfbnDzpVVaSGB9VdQrVYNdC7NJQpMn3eKug186cz9yEHmQKEllWQMhXB4Sa1TWxXspVTkSSSrpI4hsh1lMxPinCXoAjclI3ngPzwPU/KYtJxn4KUU5reb3sChQEsMRyUy2qSWFLQKJGZl7Tqh+eexEpP+NNilKfntZfEeWVG+C5qpF94gjnv6u4xPy0RQ91+f8EYl144T0A0ln2wvWNUApBMlhyDEP2YKScOmXqsKm0ZaRssItFiAWZVXgytfQ8rogANmnFwdBE+nbcLYragzkToekWt+n+XsCH5QeaNqgmoYUayfx/ykkxS1+kLp6G3Tdq9uwclvBBwZHEPv5rr7+mdiK/31FJ4qKUfhiBkwMKBTmF4tLoh7PFBzh/b8Tc6z0PYAS1xJfsdlyEWlry1qOHBUy/Y4V0reOQBFfRD0Vo3mOHClIwDcYo3Zd8o70vSnZPGC0Kon11XVyGY8ljkVtB6ISrsDoBcGNnfdN2lC1qA3MYto1V/ze/f1dnukVJCkdVSgjI3lIl9xygqxHdZ9wxF9TN673WXODeCZR7eiMR6ZDj6RKjVdLsI7ZaZIaW7JwZ38QWHpJPoaJKjGmNJxErl/bHrEWxzto4vd+WJWCv0HqoJN5/D+w="
  - secure: "lNZr62Am73BwLJGKXT0/1VKOLBdb8SQcPOfheQDwoQi9+G2Hb8sqnHqcocKYTCA8PCmnnC/hX+X8t03X5sN6yFhg3ssl1NcCzLmt9GVQ9nBSb0GuI9B2HusIq7r/yyhsbK2Fri4JfkdZG2yO5nZ8eJBRFRkn3WGZaObvrd4QEBh96PvCL1+i8r2Tf5S8ULekf2UunBrHUVCb+cQ6wErNP/fp1UXt1Vd2ekJ1xuoJPiSPXvp+KT5z+lpaja65Bvjxo19WwNqy1OkubBrwZ/jFD82LZoHT+amjmJ6fFMUDfaZnBl4rlSnCukvSXmJ8pK9C7F58joNlZ1dHf7rkduzDHCPYpJ3hWOvT2X0uZW2etxD31SleWLEv87vYGQHkiy895rGXJunnk0Nwuhzfn78nOBGXE9JSUbtZ1CuWAhYTDVbRtNOIGu32L7sDJos14WhBZfc9T3F8snrBagw2H3c3OSfd9V+X5oG35/gFam9xzPU6TQ+zBHjNrYyfcBuijJrZ0IUI3Eb979q/P2iMjSkTwFqqcC8LLy/UvcgZ9/mwBv71Jh7Js1+mwejaBzQhxHyEsKnqXqe/pOnpYQmxQhaH3sAjyB+bkCOvW1ZzoQ9eZK5Vh+p5YHZu0Idh4U4zxjaMdO9nakaUsnzCZQtSW06Pcyi+u2tYIb0mUXhy0234jMQ="
  - secure: "Ss7N3Wf+icGmqvRId5Bf52sIcKrzothR3CpFgdYqNdXgP+aMFb4MSVhDsNqoM6gnCtL5InTmWJ4P9zlMjTmlwyP0Br2TseDXgrHYhjb0pQR/MYmzoZtmRaChV0jqbYvMz2r0HC0wFrf1vyZIaAssnF1Uxf0lPddeO2HGddmIWqSm34vYyXU4GvDFeiCIkt6FwcbAHupZ1Zn8/5EikKDzYUClHFpa/XPfW8DjfqP8ZKyNH1k4KsrT9rNPBSuk39Oo/aJ9zFLbQF0c2F8P6HK+TA0WQpLepPg+adQlpYNRXzgIuV1sDRL1SCiy6ipQH13bn4jyK745l6zfxgPjIZmKYSs0aBhf0+9+5ozoSQzMrFPvnUZVsrztIlNTaK+8p8HPyLQzbVgMnmIPd4WMRcNLpilLsFlRq7DdTs8sezwSYfQCz0za5wXEr9osUYNenfnthGVZdo7RNHOA3J5POMuZjOiKKHJAswjFUitiwtLPNF17Cs7cNxqU0mUaswub/EsyAj+lYrQp80Xkkrns6qrjHuxLsZVpucNftiTSYlbQZyhYsMuKoB097RDGbAEgC/oMx9V0sTzKUNv4j0F4lRvcFtVpeEGWGHN7obATxQx6WADYr0L/G39OTpnQBjwjHcynM6ItHhqAOXJq6SLjymsap34wRjej7Me+DpJcUn7RHx0="

before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: export CF_API=https://api.ng.bluemix.net && cf-blue-green-travis && export CF_API=https://api.eu-gb.bluemix.net && cf-blue-green-travis && export CF_API=https://api.au-syd.bluemix.net && cf-blue-green-travis
  on:
    branch: master
    repo: IBM-Bluemix/go-cloudant
